org:
  quartz:
    scheduler:
      instanceId: AUTO
      instanceName: kingbbode-example
      makeSchedulerThreadDaemon : true
      interruptJobsOnShutdown  : true
    jobStore:
      clusterCheckinInterval: 20000
      driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      isClustered: true
      misfireThreshold: 60000
      tablePrefix: QRTZ_
      useProperties: false
    threadPool:
      threadCount: 5
      makeThreadsDaemons : true
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springboot
      username: junseong
      password: pass
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialization-mode: always